/*
 * sc_ui_atlas_drake.h — Drake Military sprite atlas descriptor
 *
 * Atlas: sdcard/assets/themes/drake/atlas.bin
 * Format: RGB565, 512 × 512 pixels (524 288 bytes)
 * Generated by: tools/pack_sprite_atlas.py --theme drake
 *
 * Coordinate system: (0,0) = top-left corner of the atlas bitmap.
 * All values in pixels.
 *
 * ┌────────────────────────────────────────────────────────┐
 * │  Row 0   y=0    Buttons 7× (140×56 each)               │
 * │  Row 1   y=56   Buttons cont. / Slider tracks           │
 * │  Row 2   y=112  Axes (120×120 Joystick/DPAD/HAAT)       │
 * │  Row 3   y=232  Throttle/Yaw/Rudder + Slider thumbs     │
 * │  Row 4   y=312  Jog wheel frames (96×96 × 8)            │
 * │  Row 5   y=408  Knob ring + cap (64×64 each)            │
 * │  Row 6   y=472  9-slice panel pieces                    │
 * └────────────────────────────────────────────────────────┘
 *
 * IMPORTANT: Keep these coordinates in sync with the SVG source art and the
 * atlas .bin produced by pack_sprite_atlas.py.  Re-run the packer whenever
 * the SVG layout changes.
 */
#pragma once

#include "sc_ui_sprites.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ── Atlas metadata ──────────────────────────────────────────────────────── */

static const sc_ui_atlas_meta_t SC_ATLAS_DRAKE_META = {
    .width       = 576,
    .height      = 544,
    .color_depth = 16,      /* RGB565 */
    .chroma_key  = 0x0001,  /* near-black transparent sentinel */
};

/* ── SD card path ────────────────────────────────────────────────────────── */

#define SC_ATLAS_DRAKE_PATH "S:/assets/themes/drake/atlas.bin"

/* ── Sprite rectangle table ──────────────────────────────────────────────── */
/*
 * Indexed by sc_ui_sprite_id_t.  Entry order MUST match the enum order
 * defined in sc_ui_sprites.h — verified at compile time below.
 */

static const sc_ui_sprite_rect_t SC_ATLAS_DRAKE_DESC[SC_SPRITE_COUNT] = {

    /* ── Buttons ────────────────────── x    y    w    h  ── */
    [SC_SPRITE_BTN_MOMENTARY_IDLE]   = {   0,   0, 140,  56 },
    [SC_SPRITE_BTN_MOMENTARY_ARMED]  = { 140,   0, 140,  56 },
    [SC_SPRITE_BTN_MOMENTARY_ACTIVE] = { 280,   0, 140,  56 },
    [SC_SPRITE_BTN_LATCHING_OFF]     = {   0,  56, 140,  56 },
    [SC_SPRITE_BTN_LATCHING_ON]      = { 140,  56, 140,  56 },
    [SC_SPRITE_BTN_INACTIVE]         = { 280,  56, 140,  56 },
    [SC_SPRITE_BTN_DANGER]           = { 420,   0, 140,  56 },

    /* ── Sliders ─────────────────────────────────────────── */
    [SC_SPRITE_SLIDER_TRACK_H]       = {   0,  96, 120,  24 }, /* stretch-x */
    [SC_SPRITE_SLIDER_TRACK_V]       = { 120,  96,  24, 120 }, /* stretch-y */
    [SC_SPRITE_SLIDER_THUMB]         = { 144,  96,  40,  24 }, /* shared    */

    /* ── Axes — Joystick ─────────────────────────────────── */
    [SC_SPRITE_AXIS_JOYSTICK_BASE]   = {   0, 112, 120, 120 },
    [SC_SPRITE_AXIS_JOYSTICK_THUMB]  = { 120, 112,  40,  40 },

    /* ── Axes — D-Pad ────────────────────────────────────── */
    [SC_SPRITE_AXIS_DPAD_BASE]       = { 160, 112, 120, 120 },
    [SC_SPRITE_AXIS_DPAD_UP]         = { 280, 112,  40,  36 },
    [SC_SPRITE_AXIS_DPAD_DOWN]       = { 320, 112,  40,  36 },
    [SC_SPRITE_AXIS_DPAD_LEFT]       = { 360, 112,  36,  40 },
    [SC_SPRITE_AXIS_DPAD_RIGHT]      = { 396, 112,  36,  40 },

    /* ── Axes — HAAT (2-D trackpad / head-actuated) ──────── */
    [SC_SPRITE_AXIS_HAAT_BASE]       = {   0, 232, 120, 120 },
    [SC_SPRITE_AXIS_HAAT_CURSOR]     = { 120, 232,  24,  24 },

    /* ── Axes — Throttle (vertical linear) ───────────────── */
    [SC_SPRITE_AXIS_THROTTLE_TRACK]  = { 144, 232,  44, 120 },
    [SC_SPRITE_AXIS_THROTTLE_GRIP]   = { 188, 232,  60,  20 },

    /* ── Axes — Yaw (rotary arc) ─────────────────────────── */
    [SC_SPRITE_AXIS_YAW_RING]        = { 248, 232, 120, 120 },
    [SC_SPRITE_AXIS_YAW_NEEDLE]      = { 368, 232,  10,  56 },

    /* ── Axes — Rudder (horizontal bar/pedal) ────────────── */
    [SC_SPRITE_AXIS_RUDDER_TRACK]    = {   0, 352, 256,  32 },
    [SC_SPRITE_AXIS_RUDDER_PEDAL]    = { 256, 352,  56,  40 },

    /* ── Knobs ───────────────────────────────────────────── */
    [SC_SPRITE_KNOB_RING]            = {   0, 408,  64,  64 },
    [SC_SPRITE_KNOB_CAP]             = {  64, 408,  64,  64 },

    /* ── Jog Wheel Frames (96×96, 8-frame strip) ─────────── */
    [SC_SPRITE_JOG_WHEEL_F0]         = {   0, 312,  96,  96 },
    [SC_SPRITE_JOG_WHEEL_F1]         = {  96, 312,  96,  96 },
    [SC_SPRITE_JOG_WHEEL_F2]         = { 192, 312,  96,  96 },
    [SC_SPRITE_JOG_WHEEL_F3]         = { 288, 312,  96,  96 },
    [SC_SPRITE_JOG_WHEEL_F4]         = { 384, 312,  96,  96 }, /* flips to 0 after */
    [SC_SPRITE_JOG_WHEEL_F5]         = {   0, 408,   0,   0 }, /* NOTE: reuse F0 area rotated */
    [SC_SPRITE_JOG_WHEEL_F6]         = {   0, 408,   0,   0 }, /* placeholder — see note */
    [SC_SPRITE_JOG_WHEEL_F7]         = {   0, 408,   0,   0 }, /* placeholder — see note */
    /* NOTE: F5-F7 share F0-F2 reflected via lv_image_set_angle(). Update coords
     * when the packer generates all 8 frames in the atlas. */

    /* ── 9-slice Panel ───────────────────────────────────── */
    [SC_SPRITE_PANEL_TL]             = { 128, 472,  16,  16 },
    [SC_SPRITE_PANEL_TR]             = { 144, 472,  16,  16 },
    [SC_SPRITE_PANEL_BL]             = { 160, 472,  16,  16 },
    [SC_SPRITE_PANEL_BR]             = { 176, 472,  16,  16 },
    [SC_SPRITE_PANEL_EDGE_T]         = { 192, 472,  64,   8 }, /* tile-x */
    [SC_SPRITE_PANEL_EDGE_B]         = { 256, 472,  64,   8 }, /* tile-x */
    [SC_SPRITE_PANEL_EDGE_L]         = { 320, 472,   8,  64 }, /* tile-y */
    [SC_SPRITE_PANEL_EDGE_R]         = { 328, 472,   8,  64 }, /* tile-y */
    [SC_SPRITE_PANEL_CENTER]         = { 336, 472,  64,  64 }, /* tile-xy */
};

/* Compile-time size guard */
_Static_assert(
    sizeof(SC_ATLAS_DRAKE_DESC) == sizeof(sc_ui_sprite_rect_t) * SC_SPRITE_COUNT,
    "SC_ATLAS_DRAKE_DESC entry count does not match SC_SPRITE_COUNT"
);

#ifdef __cplusplus
}
#endif
