import glob
import os

def generate():
    drake = glob.glob("components/sc_ui/assets/sprites/drake/*.bin")
    origin = glob.glob("components/sc_ui/assets/sprites/origin/*.bin")

    h_content = "#pragma once\n#include \"lvgl.h\"\n\n"
    c_content = "#include \"sc_ui_theme_sprites.h\"\n\n"

    def process(files, theme):
        nonlocal h_content, c_content
        for f in files:
            base = os.path.basename(f)
            name, _ = os.path.splitext(base)
            
            # The symbol name generated by target_add_binary_data uses the full path!
            # Example: _binary_assets_sprites_drake_btn_idle_bin_start
            sym_base = f"assets_sprites_{theme}_{name.replace('-', '_').replace('.', '_')}_bin"
            
            img_name = f"img_{theme}_{name.replace('-', '_')}"
            
            h_content += f"extern const lv_image_dsc_t {img_name};\n"
            
            c_content += f"extern const uint8_t _binary_{sym_base}_start[];\n"
            # Get dimensions from the png (which we deleted, wait... I should have saved dimensions!)
            # We can use PIL to read the bin file if we know it's RGB565? No, no size header.
            # I'll just hardcode 140x56 for buttons and others? Wait!
            pass

    # Wait, the bin files DO NOT have width and height! We MUST have the width and height for lv_image_dsc_t!
    pass

if __name__ == "__main__":
    generate()
